# 振り分けるサーバーグループを定義
upstream backend {
    # web1コンテナのポート80に振り分ける
    # max_fails=1: 1回失敗したら切り離す
    # fail_timeout=5s: 5秒後に復活を確認する
    server web1:80 max_fails=1 fail_timeout=5s;
    server web2:80 max_fails=1 fail_timeout=5s;
}

# Ibの設定
server {
    # ポート80で待ち受ける
    # 全てのURLパスに対して
    listen 80;

    location / {
        # backendグループに転送する
        proxy_pass http://backend;
        # 接続に2秒かかったらタイムアウト
        proxy_connect_timeout 2s;
        # 応答に2秒かかったらタイムアウト
        proxy_read_timeout 2s;
    }
}
